import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import WeatherComponent from '@/Components/WeatherComponent';

const Home = () => {
  return (
    <>
      <Head>
        <title>GOT-weather</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/game.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Image
            src="/map.jpg"
            alt="westerose-map"
            width={2000} 
            height={1000} 
          />
              <WeatherComponent />
        </div>
      </main>
    </>
  );
};

export default Home;
